CREATE DATABASE `ADB_Health`;
USE `ADB_Health`;

DROP TABLE daily_mycap;
DROP TABLE students;

CREATE TABLE students (
  STUDENT_ID INT NOT NULL,
  STUDENT_NAME VARCHAR(30) NOT NULL,
  LAT DECIMAL(10, 8) NOT NULL,
  LON DECIMAL(11, 8) NOT NULL,
  DT TIMESTAMP NOT NULL,
  TREATMENT VARCHAR(10) NOT NULL,
  PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE daily_mycap (
  STUDENT_ID INT NOT NULL,
  LAT DECIMAL(10, 8) NOT NULL,
  LON DECIMAL(11, 8) NOT NULL,
  DT TIMESTAMP NOT NULL,
  AQI_CURRENT INT,
  AQI_TODAY INT,
  AQI_NEXT_DAY INT,
  PRIMARY KEY (STUDENT_ID)
);

SELECT * FROM students;
SELECT * FROM daily_mycap;


TRUNCATE TABLE students;
TRUNCATE TABLE daily_mycap;

COMMIT