CREATE DATABASE `ADB_Health`;
USE `ADB_Health`;

DROP TABLE daily_mycap;
DROP TABLE students;

CREATE TABLE students (
  STUDENT_ID VARCHAR(20) NOT NULL,
  STUDENT_NAME VARCHAR(30) NOT NULL,
  LAT VARCHAR(30) NOT NULL,
  LON VARCHAR(30) NOT NULL,
  DT TIMESTAMP NOT NULL,
  TREATMENT VARCHAR(10) NOT NULL
);

CREATE TABLE daily_mycap (
  STUDENT_ID VARCHAR(20) NOT NULL,
  LAT VARCHAR(30) NOT NULL,
  LON VARCHAR(30) NOT NULL,
  DT TIMESTAMP NOT NULL,
  AQI_CURRENT INT,
  AQI_TODAY INT,
  AQI_NEXT_DAY INT
);

SELECT * FROM students;
SELECT * FROM daily_mycap;


TRUNCATE TABLE students;
TRUNCATE TABLE daily_mycap;

COMMIT